### ISSUE TITLE
spliting by sentence

### ISSUE THREAD

**Issue by un-lock-me** [behnamsabeti/LSTM_autoencoder#1]
have a question here, I am trying to figure it out why do we need to split our text to sentences if we can do that using timestamp?
To make it clear, if we feed the data to the model and say the time stamp is 60, it means the model will consider the 60 words for keeping the context. then I can not get why do you need to split the data by sentence or paragraph or whatever?

Can you please explain this?

**Comment by behnamsabeti** [comment]
In order to train a LSTM model we need to fix the length of input samples. For example we set the maximum length to 60 words and cut-off longer sequences while stretching shorter sequences with padding. You can do this with sentences, paragraphs or any other splitting strategy, but it needs to be done otherwise you will get runtime errors. I hope this answered your question. If not please explain more.

**Comment by un-lock-me** [comment]
Thanks for explaining, I actually figured it out. the thing that I am stuck in is that I want to see the features extracted. the code I have written gives me 600 features (60 seq length, 10 topics) but it does not make sense to me, I want to see for example 10 topic and for each topic for example 20 word distribution.
Do you have any idea how can I do that?

Happy Persian New Year:)
